### ISSUE TITLE
Maven pom.xml need fix for clean compile/build

### ISSUE THREAD

**Issue by srbala** [primefaces/showcase#1]
Showcase pom.xml need fix to a dependency barcode4j-light version. 2.1 version of light is not available in public maven repositories. Needs to change to full version.

**Comment by srbala** [comment]
If the showcase still want use barcode4j-light version then pom.xml barcode4j-light version should changed to 2.0.

**Comment by cagataycivici** [comment]
But code does not work with 2.0.
