### ISSUE TITLE
Input Number Demo Page Error

### ISSUE THREAD

**Issue by mfuru** [primefaces/showcase#10]
http://www.primefaces.org/showcase/error/error.xhtml

----
A unexpected error occured! Message: /ui/input/inputNumber.xhtml `@29,86` <p:inputNumber> Tag Library supports namespace: http://primefaces.org/ui, but no tag was defined for name: inputNumber

**Comment by mertsincan** [comment]
Fixed with new showcase releases. Thank you ;)

**Comment by thgunner** [comment]
How to fix this error
