### ISSUE TITLE
PaginatorTemplate extra space

### ISSUE THREAD

**Issue by sudheerj** [primefaces/showcase#11]
Hi,

  The paginator demo contains an extra space in paginator template which causes space also empty template element in the example.In the below template there is one extra space between currentpagereport and firstpagelink.

{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}

http://www.primefaces.org/showcase/ui/data/datatable/paginator.xhtml

**Comment by mertsincan** [comment]
Thanks @sudheerj :+1:
