### ISSUE TITLE
p:imageCropper showcase example code fails in portlets

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces/showcase#13]
The [`p:imageCropper`](http://www.primefaces.org/showcase/ui/multimedia/cropper.xhtml) [**`CropperView.java`**](https://github.com/primefaces/showcase/blob/master/src/main/java/org/primefaces/showcase/view/multimedia/CropperView.java#L47-L49) example code relies on the `ServletContext`, so it will not work in portlets where `externalContext.getContext()` returns a `PortletContext`.

```
ServletContext servletContext = (ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext();
String newFileName = servletContext.getRealPath("") + File.separator + "resources" + File.separator + "demo" +
    File.separator + "images" + File.separator + "crop" + File.separator + getNewImageName() + ".jpg";
```

To avoid relying on the `ServletContext`, the above code can call `externalContext.getRealPath("")` instead of `servletContext.getRealPath("")`:

```
ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
String newFileName = externalContext.getRealPath("") + File.separator + "resources" + File.separator + "demo" +
    File.separator + "images" + File.separator + "crop" + File.separator + getNewImageName() + ".jpg";
```

**Comment by tandraschko** [comment]
would be great if you could provide a PR here, too :)

**Comment by stiemannkj1** [comment]
Done: #14 :)
