### ISSUE TITLE
BUILD FAILURE: Could not validate integrity of download from http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.jar

### ISSUE THREAD

**Issue by donhuvy** [primefaces/showcase#17]
After I clone repository, then fire a command: `mvn jetty:run`, error happen:

`Microsoft Windows [Version 10.0.10586](c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>cd /d Deskotop
The system cannot find the path specified.

C:\Users\Administrator>cd Desktop

C:\Users\Administrator\Desktop>dir
 Volume in drive C has no label.
 Volume Serial Number is 0D82-10C9

 Directory of C:\Users\Administrator\Desktop

09/04/2016  08:06 SA    <DIR>          .
09/04/2016  08:06 SA    <DIR>          ..
29/09/2014  11:19 SA    <DIR>          7306OS_Code
07/04/2016  08:03 CH    <DIR>          android
19/03/2016  04:34 CH    <DIR>          Apress - Pro Spring 4 - source code
07/04/2016  08:02 CH    <DIR>          Apress - Spring boot
08/04/2016  03:28 CH    <DIR>          bar
07/04/2016  03:54 CH               563 bongdaplusdotvn.py
07/04/2016  03:54 CH             1.056 bongdaplusdotvn.pyc
07/04/2016  04:09 CH               506 brain_thunderstom.txt
01/04/2016  10:10 CH    <DIR>          desktop
25/03/2016  08:30 SA               832 Eclipse JavaEE 4.5.2.lnk
08/04/2016  02:19 CH    <DIR>          foo
08/04/2016  10:52 CH    <DIR>          KeePass
04/04/2016  10:55 CH    <DIR>          key
08/04/2016  10:26 CH            55.296 Lich on thi EMBA (Nam 2016 lop A).doc
03/04/2016  09:22 SA    <DIR>          linhnc
22/03/2016  09:48 CH    <DIR>          Manning - JUnit 4 in action - source code
11/03/2016  08:03 SA    <DIR>          MongoDB_day1 - offical slide
28/03/2016  11:32 SA    <DIR>          muabannhadatprodotcom
09/04/2016  08:06 SA    <DIR>          pm
08/04/2016  10:36 CH         8.344.435 primefaces_user_guide_5_3.pdf
06/04/2016  09:30 CH         1.570.544 thinkapjava.pdf
08/04/2016  04:55 CH            12.165 Untitled 1.odt
06/04/2016  10:34 CH        38.813.304 Vivaldi.1.0.435.40.exe
07/04/2016  07:21 CH    <DIR>          vy
               9 File(s)     48.798.701 bytes
              17 Dir(s)  48.242.176.000 bytes free

C:\Users\Administrator\Desktop>cd pm

C:\Users\Administrator\Desktop\pm>git clone https://github.com/primefaces/showcase.git
Cloning into 'showcase'...
remote: Counting objects: 8513, done.
remote: Compressing objects: 100% (49/49), done.
Receiving objects: 100% (8513/8513), 8.53 MiB | 424.00 KiB/s, done.eceiving objects: 100% (8513/8513), 8.50 MiB | 424.00 KiB/s

Resolving deltas: 100% (5037/5037), done.
Checking connectivity... done.

C:\Users\Administrator\Desktop\pm>mvn jetty:run
Terminate batch job (Y/N)?
Terminate batch job (Y/N)? y

C:\Users\Administrator\Desktop\pm>dir
 Volume in drive C has no label.
 Volume Serial Number is 0D82-10C9

 Directory of C:\Users\Administrator\Desktop\pm

09/04/2016  08:06 SA    <DIR>          .
09/04/2016  08:06 SA    <DIR>          ..
09/04/2016  08:06 SA    <DIR>          showcase
               0 File(s)              0 bytes
               3 Dir(s)  48.221.822.976 bytes free

C:\Users\Administrator\Desktop\pm>cd showcase

C:\Users\Administrator\Desktop\pm\showcase>dir
 Volume in drive C has no label.
 Volume Serial Number is 0D82-10C9

 Directory of C:\Users\Administrator\Desktop\pm\showcase

09/04/2016  08:06 SA    <DIR>          .
09/04/2016  08:06 SA    <DIR>          ..
09/04/2016  08:06 SA                73 .gitignore
09/04/2016  08:06 SA            10.850 pom.xml
09/04/2016  08:06 SA             1.459 README.md
09/04/2016  08:06 SA    <DIR>          src
               3 File(s)         12.382 bytes
               3 Dir(s)  48.221.822.976 bytes free

C:\Users\Administrator\Desktop\pm\showcase>mvn jetty:run
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building primefaces-showcase 6.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> jetty-maven-plugin:8.1.9.v20130131:run (default-cli) > test-compile @ showcase >>>
Downloading: http://repository.primefaces.org/rome/rome/1.0/rome-1.0.pom
Downloading: https://repo.maven.apache.org/maven2/rome/rome/1.0/rome-1.0.pom
Downloaded: https://repo.maven.apache.org/maven2/rome/rome/1.0/rome-1.0.pom (7 KB at 4.4 KB/sec)
Downloading: http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.pom
[WARNING] Could not validate integrity of download from http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.pom: Checksum validation failed, no checksums available
[WARNING] Checksum validation failed, no checksums available for http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.pom
Downloaded: http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.pom (473 B at 0.3 KB/sec)
Downloading: http://repository.primefaces.org/org/primefaces/primefaces/6.0-SNAPSHOT/maven-metadata.xml
Downloading: http://repository.primefaces.org/org/primefaces/primefaces/6.0-SNAPSHOT/primefaces-6.0-SNAPSHOT.pom
[WARNING] The POM for org.primefaces:primefaces:jar:6.0-SNAPSHOT is missing, no dependency information available
Downloading: http://repository.primefaces.org/org/glassfish/javax.faces/2.2.10/javax.faces-2.2.10.pom
Downloading: https://repo.maven.apache.org/maven2/org/glassfish/javax.faces/2.2.10/javax.faces-2.2.10.pom
Downloaded: https://repo.maven.apache.org/maven2/org/glassfish/javax.faces/2.2.10/javax.faces-2.2.10.pom (11 KB at 24.7 KB/sec)
Downloading: http://repository.primefaces.org/org/atmosphere/atmosphere-runtime/2.4.3/atmosphere-runtime-2.4.3.pom
Downloading: https://repo.maven.apache.org/maven2/org/atmosphere/atmosphere-runtime/2.4.3/atmosphere-runtime-2.4.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/atmosphere/atmosphere-runtime/2.4.3/atmosphere-runtime-2.4.3.pom (12 KB at 27.6 KB/sec)
Downloading: http://repository.primefaces.org/org/atmosphere/atmosphere-project/2.4.3/atmosphere-project-2.4.3.pom
Downloading: https://repo.maven.apache.org/maven2/org/atmosphere/atmosphere-project/2.4.3/atmosphere-project-2.4.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/atmosphere/atmosphere-project/2.4.3/atmosphere-project-2.4.3.pom (25 KB at 41.8 KB/sec)
Downloading: http://repository.primefaces.org/rome/rome/1.0/rome-1.0.jar
Downloading: http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.jar
Downloading: http://repository.primefaces.org/org/primefaces/primefaces/6.0-SNAPSHOT/primefaces-6.0-SNAPSHOT.jar
Downloading: http://repository.primefaces.org/junit/junit/3.8/junit-3.8.jar
Downloading: http://repository.primefaces.org/org/glassfish/javax.faces/2.2.10/javax.faces-2.2.10.jar
Downloading: http://repository.primefaces.org/org/atmosphere/atmosphere-runtime/2.4.3/atmosphere-runtime-2.4.3.jar
[WARNING] Could not validate integrity of download from http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.jar: Checksum validation failed, no checksums available
[WARNING] Checksum validation failed, no checksums available for http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.jar
Downloaded: http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.jar (226 KB at 57.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/rome/rome/1.0/rome-1.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/glassfish/javax.faces/2.2.10/javax.faces-2.2.10.jar
Downloading: https://repo.maven.apache.org/maven2/org/atmosphere/atmosphere-runtime/2.4.3/atmosphere-runtime-2.4.3.jar
Downloading: https://repo.maven.apache.org/maven2/junit/junit/3.8/junit-3.8.jar
Downloaded: https://repo.maven.apache.org/maven2/rome/rome/1.0/rome-1.0.jar (215 KB at 183.7 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/junit/junit/3.8/junit-3.8.jar (119 KB at 63.6 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/atmosphere/atmosphere-runtime/2.4.3/atmosphere-runtime-2.4.3.jar (844 KB at 150.8 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/glassfish/javax.faces/2.2.10/javax.faces-2.2.10.jar (3058 KB at 290.4 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.984 s
[INFO] Finished at: 2016-04-09T08:07:37+07:00
[INFO] Final Memory: 9M/134M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project showcase: Could not resolve dependencies for project org.primefaces:showcase:war:6.0-SNAPSHOT: Could not find artifact org.primefaces:primefaces:jar:6.0-SNAPSHOT in prime-repo (http://repository.primefaces.org) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

C:\Users\Administrator\Desktop\pm\showcase>

C:\Users\Administrator\Desktop\pm\showcase>`

**I propose changing these lines: https://github.com/primefaces/showcase/blob/master/pom.xml#L142-L146**

**become** 
`<dependency>
    <groupId>net.sf.barcode4j</groupId>
    <artifactId>barcode4j-light</artifactId>
    <version>2.0</version>
</dependency>`
![primeface](https://cloud.githubusercontent.com/assets/1328316/14400913/c3aa4db6-fe2a-11e5-9b67-3310ec1fa8e5.jpg)

**Comment by donhuvy** [comment]
Other error:
`Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>cd /d Deskotop
The system cannot find the path specified.

C:\Users\Administrator>cd Desktop

C:\Users\Administrator\Desktop>dir
 Volume in drive C has no label.
 Volume Serial Number is 0D82-10C9

 Directory of C:\Users\Administrator\Desktop

09/04/2016  08:06 SA    <DIR>          .
09/04/2016  08:06 SA    <DIR>          ..
29/09/2014  11:19 SA    <DIR>          7306OS_Code
07/04/2016  08:03 CH    <DIR>          android
19/03/2016  04:34 CH    <DIR>          Apress - Pro Spring 4 - source code
07/04/2016  08:02 CH    <DIR>          Apress - Spring boot
08/04/2016  03:28 CH    <DIR>          bar
07/04/2016  03:54 CH               563 bongdaplusdotvn.py
07/04/2016  03:54 CH             1.056 bongdaplusdotvn.pyc
07/04/2016  04:09 CH               506 brain_thunderstom.txt
01/04/2016  10:10 CH    <DIR>          desktop
25/03/2016  08:30 SA               832 Eclipse JavaEE 4.5.2.lnk
08/04/2016  02:19 CH    <DIR>          foo
08/04/2016  10:52 CH    <DIR>          KeePass
04/04/2016  10:55 CH    <DIR>          key
08/04/2016  10:26 CH            55.296 Lich on thi EMBA (Nam 2016 lop A).doc
03/04/2016  09:22 SA    <DIR>          linhnc
22/03/2016  09:48 CH    <DIR>          Manning - JUnit 4 in action - source code
11/03/2016  08:03 SA    <DIR>          MongoDB_day1 - offical slide
28/03/2016  11:32 SA    <DIR>          muabannhadatprodotcom
09/04/2016  08:06 SA    <DIR>          pm
08/04/2016  10:36 CH         8.344.435 primefaces_user_guide_5_3.pdf
06/04/2016  09:30 CH         1.570.544 thinkapjava.pdf
08/04/2016  04:55 CH            12.165 Untitled 1.odt
06/04/2016  10:34 CH        38.813.304 Vivaldi.1.0.435.40.exe
07/04/2016  07:21 CH    <DIR>          vy
               9 File(s)     48.798.701 bytes
              17 Dir(s)  48.242.176.000 bytes free

C:\Users\Administrator\Desktop>cd pm

C:\Users\Administrator\Desktop\pm>git clone https://github.com/primefaces/showcase.git
Cloning into 'showcase'...
remote: Counting objects: 8513, done.
remote: Compressing objects: 100% (49/49), done.
Receiving objects: 100% (8513/8513), 8.53 MiB | 424.00 KiB/s, done.eceiving objects: 100% (8513/8513), 8.50 MiB | 424.00 KiB/s

Resolving deltas: 100% (5037/5037), done.
Checking connectivity... done.

C:\Users\Administrator\Desktop\pm>mvn jetty:run
Terminate batch job (Y/N)?
Terminate batch job (Y/N)? y

C:\Users\Administrator\Desktop\pm>dir
 Volume in drive C has no label.
 Volume Serial Number is 0D82-10C9

 Directory of C:\Users\Administrator\Desktop\pm

09/04/2016  08:06 SA    <DIR>          .
09/04/2016  08:06 SA    <DIR>          ..
09/04/2016  08:06 SA    <DIR>          showcase
               0 File(s)              0 bytes
               3 Dir(s)  48.221.822.976 bytes free

C:\Users\Administrator\Desktop\pm>cd showcase

C:\Users\Administrator\Desktop\pm\showcase>dir
 Volume in drive C has no label.
 Volume Serial Number is 0D82-10C9

 Directory of C:\Users\Administrator\Desktop\pm\showcase

09/04/2016  08:06 SA    <DIR>          .
09/04/2016  08:06 SA    <DIR>          ..
09/04/2016  08:06 SA                73 .gitignore
09/04/2016  08:06 SA            10.850 pom.xml
09/04/2016  08:06 SA             1.459 README.md
09/04/2016  08:06 SA    <DIR>          src
               3 File(s)         12.382 bytes
               3 Dir(s)  48.221.822.976 bytes free

C:\Users\Administrator\Desktop\pm\showcase>mvn jetty:run
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building primefaces-showcase 6.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> jetty-maven-plugin:8.1.9.v20130131:run (default-cli) > test-compile @ showcase >>>
Downloading: http://repository.primefaces.org/rome/rome/1.0/rome-1.0.pom
Downloading: https://repo.maven.apache.org/maven2/rome/rome/1.0/rome-1.0.pom
Downloaded: https://repo.maven.apache.org/maven2/rome/rome/1.0/rome-1.0.pom (7 KB at 4.4 KB/sec)
Downloading: http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.pom
[WARNING] Could not validate integrity of download from http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.pom: Checksum validation failed, no checksums available
[WARNING] Checksum validation failed, no checksums available for http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.pom
Downloaded: http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.pom (473 B at 0.3 KB/sec)
Downloading: http://repository.primefaces.org/org/primefaces/primefaces/6.0-SNAPSHOT/maven-metadata.xml
Downloading: http://repository.primefaces.org/org/primefaces/primefaces/6.0-SNAPSHOT/primefaces-6.0-SNAPSHOT.pom
[WARNING] The POM for org.primefaces:primefaces:jar:6.0-SNAPSHOT is missing, no dependency information available
Downloading: http://repository.primefaces.org/org/glassfish/javax.faces/2.2.10/javax.faces-2.2.10.pom
Downloading: https://repo.maven.apache.org/maven2/org/glassfish/javax.faces/2.2.10/javax.faces-2.2.10.pom
Downloaded: https://repo.maven.apache.org/maven2/org/glassfish/javax.faces/2.2.10/javax.faces-2.2.10.pom (11 KB at 24.7 KB/sec)
Downloading: http://repository.primefaces.org/org/atmosphere/atmosphere-runtime/2.4.3/atmosphere-runtime-2.4.3.pom
Downloading: https://repo.maven.apache.org/maven2/org/atmosphere/atmosphere-runtime/2.4.3/atmosphere-runtime-2.4.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/atmosphere/atmosphere-runtime/2.4.3/atmosphere-runtime-2.4.3.pom (12 KB at 27.6 KB/sec)
Downloading: http://repository.primefaces.org/org/atmosphere/atmosphere-project/2.4.3/atmosphere-project-2.4.3.pom
Downloading: https://repo.maven.apache.org/maven2/org/atmosphere/atmosphere-project/2.4.3/atmosphere-project-2.4.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/atmosphere/atmosphere-project/2.4.3/atmosphere-project-2.4.3.pom (25 KB at 41.8 KB/sec)
Downloading: http://repository.primefaces.org/rome/rome/1.0/rome-1.0.jar
Downloading: http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.jar
Downloading: http://repository.primefaces.org/org/primefaces/primefaces/6.0-SNAPSHOT/primefaces-6.0-SNAPSHOT.jar
Downloading: http://repository.primefaces.org/junit/junit/3.8/junit-3.8.jar
Downloading: http://repository.primefaces.org/org/glassfish/javax.faces/2.2.10/javax.faces-2.2.10.jar
Downloading: http://repository.primefaces.org/org/atmosphere/atmosphere-runtime/2.4.3/atmosphere-runtime-2.4.3.jar
[WARNING] Could not validate integrity of download from http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.jar: Checksum validation failed, no checksums available
[WARNING] Checksum validation failed, no checksums available for http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.jar
Downloaded: http://repository.primefaces.org/net/sf/barcode4j/barcode4j-light/2.1/barcode4j-light-2.1.jar (226 KB at 57.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/rome/rome/1.0/rome-1.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/glassfish/javax.faces/2.2.10/javax.faces-2.2.10.jar
Downloading: https://repo.maven.apache.org/maven2/org/atmosphere/atmosphere-runtime/2.4.3/atmosphere-runtime-2.4.3.jar
Downloading: https://repo.maven.apache.org/maven2/junit/junit/3.8/junit-3.8.jar
Downloaded: https://repo.maven.apache.org/maven2/rome/rome/1.0/rome-1.0.jar (215 KB at 183.7 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/junit/junit/3.8/junit-3.8.jar (119 KB at 63.6 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/atmosphere/atmosphere-runtime/2.4.3/atmosphere-runtime-2.4.3.jar (844 KB at 150.8 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/glassfish/javax.faces/2.2.10/javax.faces-2.2.10.jar (3058 KB at 290.4 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.984 s
[INFO] Finished at: 2016-04-09T08:07:37+07:00
[INFO] Final Memory: 9M/134M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project showcase: Could not resolve dependencies for project org.primefaces:showcase:war:6.0-SNAPSHOT: Could not find artifact org.primefaces:primefaces:jar:6.0-SNAPSHOT in prime-repo (http://repository.primefaces.org) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

C:\Users\Administrator\Desktop\pm\showcase>

C:\Users\Administrator\Desktop\pm\showcase>mvn clean
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building primefaces-showcase 6.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ showcase ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.598 s
[INFO] Finished at: 2016-04-09T08:15:16+07:00
[INFO] Final Memory: 7M/72M
[INFO] ------------------------------------------------------------------------

C:\Users\Administrator\Desktop\pm\showcase>mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building primefaces-showcase 6.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.primefaces:primefaces:jar:6.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.044 s
[INFO] Finished at: 2016-04-09T08:15:23+07:00
[INFO] Final Memory: 7M/102M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project showcase: Could not resolve dependencies for project org.primefaces:showcase:war:6.0-SNAPSHOT: Failure to find org.primefaces:primefaces:jar:6.0-SNAPSHOT in http://repository.primefaces.org was cached in the local repository, resolution will not be reattempted until the update interval of prime-repo has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

C:\Users\Administrator\Desktop\pm\showcase>mvn clean
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building primefaces-showcase 6.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ showcase ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.606 s
[INFO] Finished at: 2016-04-09T08:15:34+07:00
[INFO] Final Memory: 7M/72M
[INFO] ------------------------------------------------------------------------

C:\Users\Administrator\Desktop\pm\showcase>mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building primefaces-showcase 6.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.primefaces:primefaces:jar:6.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.142 s
[INFO] Finished at: 2016-04-09T08:15:46+07:00
[INFO] Final Memory: 9M/107M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project showcase: Could not resolve dependencies for project org.primefaces:showcase:war:6.0-SNAPSHOT: Failure to find org.primefaces:primefaces:jar:6.0-SNAPSHOT in http://repository.primefaces.org was cached in the local repository, resolution will not be reattempted until the update interval of prime-repo has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

C:\Users\Administrator\Desktop\pm\showcase>mvn jetty:run
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building primefaces-showcase 6.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> jetty-maven-plugin:8.1.9.v20130131:run (default-cli) > test-compile @ showcase >>>
[WARNING] The POM for org.primefaces:primefaces:jar:6.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.035 s
[INFO] Finished at: 2016-04-09T08:15:57+07:00
[INFO] Final Memory: 7M/107M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project showcase: Could not resolve dependencies for project org.primefaces:showcase:war:6.0-SNAPSHOT: Failure to find org.primefaces:primefaces:jar:6.0-SNAPSHOT in http://repository.primefaces.org was cached in the local repository, resolution will not be reattempted until the update interval of prime-repo has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

C:\Users\Administrator\Desktop\pm\showcase>`

**Comment by tandraschko** [comment]
you need do build /mvn install primefaces first
