### ISSUE TITLE
Unable to build the project (SSL-Problem)

### ISSUE THREAD

**Issue by DominikLudwig1995** [primefaces/showcase#21]
`[ERROR] Failed to execute goal on project showcase: Could not resolve dependencies for project org.primefaces:showcase:war:6.1-SNAPSHOT: Failed to collect dependencies for [javax.servlet:servlet-api:jar:2.5 (provided), javax.servlet.jsp:jsp-api:jar:2.1 (provided), commons-logging:commons-logging:jar:1.1.1 (compile), commons-lang:commons-lang:jar:2.6 (compile), org.hibernate:hibernate-validator:jar:5.0.1.Final (compile), org.apache.poi:poi:jar:3.7 (compile), org.apache.poi:poi-ooxml:jar:3.7 (compile), com.lowagie:itext:jar:2.1.7 (compile), commons-fileupload:commons-fileupload:jar:1.3 (compile), commons-io:commons-io:jar:2.2 (compile), rome:rome:jar:1.0 (compile), org.twitter4j:twitter4j-core:jar:3.0.5 (compile), javax.inject:javax.inject:jar:1 (compile), org.slf4j:slf4j-simple:jar:1.6.1 (compile), org.primefaces.themes:all-themes:jar:1.0.10 (compile), net.sourceforge.barbecue:barbecue:jar:1.5-beta1 (compile), jfree:jfreechart:jar:1.0.0 (compile), net.glxn:qrgen:jar:1.4 (compile), net.sf.barcode4j:barcode4j-light:jar:2.1 (compile), org.primefaces:primefaces:jar:6.1.RC2-SNAPSHOT (compile), org.glassfish:javax.faces:jar:2.2.10 (compile), org.atmosphere:atmosphere-runtime:jar:2.4.6 (compile)]: Failed to read artifact descriptor for org.primefaces.themes:all-themes:jar:1.0.10: Could not transfer artifact org.primefaces.themes:all-themes:pom:1.0.10 from/to prime-repo (http://repository.primefaces.org): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]`

**Comment by mertsincan** [comment]
Can you please try it after changing 6.1.RC2-SNAPSHOT with 6.1.RC1?

**Comment by DominikLudwig1995** [comment]
Hi, I changed the Version of Primefaces to 6.1.RC1 and get the same Exception

**Comment by jposes22** [comment]
I spend over 6 hours and fixed.
First I use firefox and donwload Cert from http://repository.primefaces.org. Next with command lines I added to Java certs (lib/security/cacerts) and works fine.

**Comment by DominikLudwig1995** [comment]
Its work
