### ISSUE TITLE
Unable run from source

### ISSUE THREAD

**Issue by tfe2012** [primefaces/showcase#22]
Hi i try run from source. Then run "mvn package" I get error:

[ERROR] Failed to execute goal on project showcase: Could not resolve dependencies for project org.primefaces:showcase:war:6.1-SNAPSHOT: Failure to find org.primefaces:primefaces:jar:6.1.RC2-SNAPSHOT in http://repository.primefaces.org was cached in the local repository, resolution will not be reattempted until the update interval of prime-repo has elapsed or updates are forced -> [Help 1]

**Comment by tfe2012** [comment]
If I change version to "LATEST"

I get another error:

[ERROR] /Users/michail/IdeaProjects/showcase/src/main/java/org/primefaces/showcase/view/data/OrganigramView.java:[18,42] error: package org.primefaces.component.organigram does not exist

**Comment by mertsincan** [comment]
Can you please try it after changing 6.1.RC2-SNAPSHOT with 6.1.RC1?

**Comment by tfe2012** [comment]
It's works with 6.1.RC1

**Comment by tandraschko** [comment]
Works fine for me.
