### ISSUE TITLE
Doesn't work page

### ISSUE THREAD

**Issue by tfe2012** [primefaces/showcase#24]
Hi I get error on page:

https://www.primefaces.org/showcase/ui/data/gmap/markers.xhtml

<img width="1436" alt="screen shot 2017-03-29 at 11 37 02" src="https://cloud.githubusercontent.com/assets/8733714/24445842/0eb2edd0-1474-11e7-9c13-e14e5191d3d8.png">

**Comment by tandraschko** [comment]
Works fine for me.
