### ISSUE TITLE
Suggestion: Update the Showcase to use CDI annotations and implement Serializable as the javax.faces.bean are deprecated in JSF 2.3

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/showcase#26]
@ManagedBean(name="abc")  ->  @Named("abc")
@*Scoped -> javax.enterprise.context.*Scoped
All CDI Beans should implement "Serializable"

**Comment by tandraschko** [comment]
CDI beans must not implement serializable, only View and SessionScoped.
As PrimeFaces also works with JSF 2.0, i don't see any reason to migrate the whole showcase for now.

**Comment by cnsgithub** [comment]
Well it depends, if you want to adhere to JSF 2.2 and thus JavaEE 7 (the showcase it self is saying that it runs on mojarra 2.2.x, it would be more 'correct' to use the javax Annotations and not the @ManagedBeans ones. When the Showcase is updated to JSF 2.3 one day it probaly has to be done then anyway.

I just noticed, that each time i want to test something from the Showcase, the annotations have to be adapted for it to run properly on JSF 2.3.  (using WildFly). Now i see the Showcase is hosted on Jetty - so i don't know about that.

**Comment by tandraschko** [comment]
Thats the problem :D
There are still users which are using JSF with Spring e.g. - So we would need to have JSF ManagedBeans, CDI and even Spring.
I think JSF managedBeans are the common way for now and there are only deprecated and are still working on JSF 2.3!

**Comment by tandraschko** [comment]
Lets do this later, when we only CDI is supported in the future. Currently we still support jSF 2.0.
