### ISSUE TITLE
Push not working

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/showcase#27]
If you have 2 windows and click on the button the other page is not updated: https://www.primefaces.org/showcase/push/counter.xhtml

**Comment by myset** [comment]
Hi, 
There's an issue of security ... within https://www.primefaces.org/showcase/push/counter.xhtml is called https://www.primefaces.org:8080/....)

You could try - http://www.primefaces.org:8080/showcase/push/counter.xhtml

This is a small fix for the committers team ...

**Comment by tandraschko** [comment]
It conflicts and Push is already deprecated. Will close it for now.
