### ISSUE TITLE
In <p:carousel> showcase may be with a mistaken in <p:graphicImage> tag

### ISSUE THREAD

**Issue by talessouza** [primefaces/showcase#30]
**For <p:graphicImage>tag:**
During my tests, when I use a image inside  the project (jpg, gif, png) only works pointing the relative path in "value" atribute, not in the "name" atribute, like in carousel showcase examples.

Thank you.

**Comment by tandraschko** [comment]
If you have a issue with a component, please create a issue with all details and examples in the "primefaces" issue tracker.

**Comment by talessouza** [comment]
Thomas, OK!, but I believe it's not a issue with a component, because the components works. The issue is with the showcase because may be it's with a mistaken with the use of <p:graphicImage> tag. 

Where the showcase was to use the attribute "value", it is using the attribute "name". Note below:

In the line 4 of [primefaces carousel showcase site](https://www.primefaces.org/showcase/ui/data/carousel.xhtml)
![showcase-issue](https://user-images.githubusercontent.com/21321981/28878087-9eccfd80-7774-11e7-9628-403d7e441afd.PNG)

Thank you again.
