### ISSUE TITLE
Why was the documentation tab removed?

### ISSUE THREAD

**Issue by thatsIch** [primefaces/showcase#33]
In https://github.com/primefaces/showcase/commit/3e89566ac95c4330bda5735e5b08832de8fce9d3 the documentation tab was removed. Imo it was a really useful feature. I see no issue reference or any other indication why it was removed.

In case it stays removed, do we get something similar or better back?

Cheers,
Ich

**Comment by tandraschko** [comment]
@mertsincan Thats a question for you?!

**Comment by Quix0r** [comment]
Yes, he asks why the documentation has been removed with the named commit. Maybe it has been moved to a wiki for centralized handling?

**Comment by Quix0r** [comment]
Then maybe this belongs into forums?

**Comment by thatsIch** [comment]
The special feature was, that it directly jumped to the specific part of the documentation PDF. While searching for `p:dataTable` it will not show you all the hundreds of other hits.

**Comment by tandraschko** [comment]
the old showcase is deprecated, closing this issue now
