### ISSUE TITLE
Error uploading files

### ISSUE THREAD

**Issue by mallorygiles** [primefaces/showcase#34]
**Update:**
This actually happens with even just 1 file uploaded. It happens on all fileupload pages except basic.

**Original:**
On the file upload pages (single, multiple, and drag & drop), if more than 1 file is selected, I receive an error after clicking upload. I tried in firefox and chrome. I've added screen shots of what I did and the resulting error. Is this an issue with the code in showcase, or is this a general issue with the fileupload component?

![file_upload_files_selected](https://user-images.githubusercontent.com/12798815/29890549-fe2b4778-8d95-11e7-8a91-a79487646559.PNG)
![file_upload_error_msg](https://user-images.githubusercontent.com/12798815/29890550-fe2bcef0-8d95-11e7-991a-0d8d4f913ebf.PNG)

**Comment by tandraschko** [comment]
Problem with commons-fileupload and newer jetty versions. See https://github.com/primefaces/primefaces/issues/2909
