### ISSUE TITLE
CarService.java misses Arrays variable

### ISSUE THREAD

**Issue by Germano0** [primefaces/showcase#35]
https://www.primefaces.org/showcase/ui/data/datatable/basic.xhtml in particular `CarService.java`
generates error
```
Error:(79, 16) java: cannot find symbol
  symbol:   variable Arrays
  location: class org.primefaces.showcase.service.CarService
```
at lines
`return Arrays.asList(colors);`
`return Arrays.asList(brands);`

**Comment by tandraschko** [comment]
Works fine for me
