### ISSUE TITLE
Show case remove

### ISSUE THREAD

**Issue by RobertoFloro** [primefaces/showcase#41]
Hi, could anyone help me? A some time ago I saw a primeface showcase whit DragDrop like PiperDrive, when did it remove?

**Comment by tandraschko** [comment]
Questions -> Forum.

**Comment by RobertoFloro** [comment]
Sorry. You know about what do i speaking?

**Comment by tandraschko** [comment]
No sorry but this is a issue tracker, not a plattform for questsions. We have a forum for this case.
