### ISSUE TITLE
Enable GZIP Compression on Showcase

### ISSUE THREAD

**Issue by melloware** [primefaces/showcase#52]
Google Pagespeed is reporting its not compressed.

![image](https://user-images.githubusercontent.com/4399574/32903483-19302a7e-cac3-11e7-8d05-057854199679.png)

**Comment by melloware** [comment]
Can be done with Omnifaces filter if you can't control compression at the container.

```xml
<filter>
    <filter-name>gzipResponseFilter</filter-name>
    <filter-class>org.omnifaces.filter.GzipResponseFilter</filter-class>
</filter>
<filter-mapping>
    <filter-name>gzipResponseFilter</filter-name>
    <servlet-name>facesServlet</servlet-name>
    <dispatcher>REQUEST</dispatcher>
    <dispatcher>ERROR</dispatcher>
</filter-mapping>
```

**Comment by tandraschko** [comment]
@cagataycivici @mertsincan could you enable gzip on your server? It's a simple config both in apache or nginx.
