### ISSUE TITLE
Missing an update in the showcase for the element fileupload

### ISSUE THREAD

**Issue by AlexisPasquier** [primefaces/showcase#6]
In your showcase for the **fileupload** element in mode 'Simple' or 'Multiple' when I add 3 files and clic to *Import* every thing is fine.
But when I want to add a new file an error message is displayed 
>Maximum number of files exceeded

Or I have already import all my file, I just want re-import a another file.
To fix this we use @this in **update** attribut.

But I don't know if this a real issue, or if this is the desired behavior.

**Comment by mertsincan** [comment]
Please try after removing fileLimit="3" on p:fileupload

**Comment by AlexisPasquier** [comment]
Yes if I remove *fileLimit="3"* i can add file much as I want.
What I want is to replace the three previous file three new, I can't because fileupload keep in cache (I supposed) the three previous file.

I hope I'm clear, because isn't an important Issue and english isn't my native language
