### ISSUE TITLE
Meter Gauge example 

### ISSUE THREAD

**Issue by ghobona** [primefaces/showcase#63]
The meter gauge example refers to a chartBean object in the xhtml but the example java code is a class called ChartView. This results in an exception being thrown. Suggest changing the name of the object in the xhtml from chartBean to chartView.

src/main/webapp/ui/chart/metergauge.xhtml

**Comment by cnsgithub** [comment]
It's just the sample xhtml code shown. The showcase itself is working correctly. Fixed in https://github.com/primefaces/showcase/pull/68.
