### ISSUE TITLE
PrimeFaces-6.2.RC1 - Mobile showcase CSS lost

### ISSUE THREAD

**Issue by djmj** [primefaces/showcase#65]
Current PrimeFaces mobile showcase using PrimeFaces-6.2.RC1 has Javascript and CSS issues.
It can be seen on accordion and overlaypanel does not work at all.

https://i.imgur.com/72bZ74C.jpg

**Comment by tandraschko** [comment]
it's only broken in the showcase or why do you create the issue here?

**Comment by djmj** [comment]
I don't know, have not tested 6.2 yet. Just had a quick look at the showcase page.

**Comment by tandraschko** [comment]
Both are working fine for me.

**Comment by djmj** [comment]
Maybe some missconfiguration from deployment of production showcase. Not working on my mobilephone also: 
https://www.primefaces.org/showcase/mobile/dataList.xhtml

**Comment by tandraschko** [comment]
Yep, not sure.
It would be great if you could check that and provide a PR.
You know that mobile is already deprecated and will be removed. So i personally won't invest any time to fix it.

**Comment by tandraschko** [comment]
mobile removed -> will close the ticket
