### ISSUE TITLE
The AddRow functionality is missing in the showcase.

### ISSUE THREAD

**Issue by ssibitz** [primefaces/showcase#73]
As i am using Primefaces 6.2 i got an exception on adding a new row
which currently will be handled with the ticket #3564 .

So i am missing a short description on how to add a new row
to an existing datatable.

I searched across the internet and found out the solution
which i give you back as PR to please include it into the showcase:
[PR 72](https://github.com/primefaces/showcase/pull/72)

**Comment by melloware** [comment]
@ssibitz I think you can close this as AddRow is now in the Showcase Facelift: https://www.primefaces.org/showcase/ui/data/datatable/addRow.xhtml
