### ISSUE TITLE
mvn package FAILED

### ISSUE THREAD

**Issue by my-staffmanager-software** [primefaces/showcase#83]
mvn clean -> SUCCESS
mvn package -> FAILED

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building primefaces-showcase 6.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.primefaces:primefaces:jar:6.3-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.911 s
[INFO] Finished at: 2018-05-09T10:11:56+01:00
[INFO] Final Memory: 9M/32M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project showcase: Could not resolve dependencies for project org.primefaces:showcase:war:6.3-SNAPSHOT: Failure to find org.primefaces:primefaces:jar:6.3-SNAPSHOT in http://repository.primefaces.org was cached in the local repository, resolution will not be reattempted until the update interval of prime-repo has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]

**Comment by tandraschko** [comment]
Showcase master depends on primefaces master.
