### ISSUE TITLE
add 'supported since' to showcase for LinkButton new component

### ISSUE THREAD

**Issue by kukel** [primefaces/showcase#88]
For this component: https://github.com/primefaces/primefaces/issues/3613

This used to be done for elite or new releases. People start running into 'issues': https://stackoverflow.com/questions/50801378/trouble-implementing-primefaces-link-button

And keep doing this for new/other components as well.

**Comment by tandraschko** [comment]
A PR is very welcome!

**Comment by tandraschko** [comment]
done in the facelift
