### ISSUE TITLE
primefaces-6.3-SNAPSHOT.jar not in repository

### ISSUE THREAD

**Issue by vicruz** [primefaces/showcase#89]
The dependency:
```
<dependency>
   <groupId>org.primefaces</groupId>
   <artifactId>primefaces</artifactId>
   <version>6.3-SNAPSHOT</version>
</dependency>
```
Is in none repository, non _https://repository.primefaces.org_ neither _mvnrepository_
Where can I download this jar?

**Comment by tandraschko** [comment]
You cant, you need to build by source
