### ISSUE TITLE
Provide showcase for testing CSP integration

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/showcase#91]
A showcase should be added to allow for integration testing of the new CSP features introduced with https://github.com/primefaces/primefaces/pull/3884. 

Some brainstorming:
- use `p:wizard`
- test just one case in every step
- add _Check functionality_ button
- add _Validate CSP_ button (use https://cspvalidator.org/ to actually validate)
- show CSP header
- do some javascript on success, e.g. `alert('PASS');`
- possible steps:
   1. JS event handlers
   2. JS URI handlers
   3. `p:ajax`
   4. `f:ajax`
   5. JS event handlers in partial response
   6. JS URI handlers in partial response
   7. `script` in partial response
   8. `eval` in partial response
   9. pre-existing nonce

I accept this issue myself.

**Comment by melloware** [comment]
@cnsgithub I think you want to close this ticket and move it here: https://github.com/primefaces/showcase-facelift

**Comment by cnsgithub** [comment]
Oops, I didn't know that the old showcase is deprecated. Thanks. https://github.com/primefaces/showcase-facelift/issues/6
