### ISSUE TITLE
6.3-SNAPSHOT: Failure to find org.primefaces

### ISSUE THREAD

**Issue by VerifierIntegerAssignment** [primefaces/showcase#92]
Hi i try run from source. Then run "mvn package" I get error:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.064 s
[INFO] Finished at: 2018-08-10T22:02:48+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project showcase: Could not resolve dependencies for project org.primefaces:showcase:war:6.3-SNAPSHOT: Failure to find org.primefaces:primefaces:jar:6.3-SNAPSHOT in http://repository.primefaces.org was cached in the local repository, resolution will not be reattempted until the update interval of prime-repo has elapsed or updates are forced -> [Help 1]

**Comment by tandraschko** [comment]
check our wiki to build from source ;)
