### ISSUE TITLE
Tag 6.2 missing

### ISSUE THREAD

**Issue by Betlista** [primefaces/showcase#93]
Hi,

showcase is in version 6.3-SNAPSHOT currently and there is no 6.2 tag on GitHub.

BR,
Betlista

**Comment by tandraschko** [comment]
yup but the showcase is also deprecated now and the facelift is based on 6.3x -> so won't fix

**Comment by pzygielo** [comment]
Perhaps dead link for showcase-6.2.war tag at https://www.primefaces.org/downloads/ could be fixed then?

**Comment by tandraschko** [comment]
If you search the correct revision, i could make one ;)

**Comment by tandraschko** [comment]
created
