### ISSUE TITLE
LazyCarDataModel missing from Datatable Lazy showcase, so most important part is missing

### ISSUE THREAD

**Issue by open-gdsn** [primefaces/showcase#94]
This makes the showcase effectively not very useful is since it is now hard to know what and how to implement things.

This might also be the cause of questions like https://stackoverflow.com/questions/56111377/where-do-the-values-in-a-pdatatable-for-the-currentpagereporttemplate-come-from

**Comment by tandraschko** [comment]
fixed: https://github.com/primefaces/showcase-facelift/commit/207a6b8ee4df113f0bf492f5b49a892e7ca4af5b
